let p = "images/image prompts/",
    imgs = {
        baby: p + "baby.jpg",
        balloon: p + "balloon.jpg",
        banana: p + "banana.jpg",
        basket: p + "basket.jpg",
        bicycle: p + "bicycle.jpg",
        bird: p + "bird.jpg",
        boat: p + "boat.jpg",
        bowl: p + "bowl.jpg",
        bread: p + "bread.jpg",
        burger: p + "burger.jpg",
        cake: p + "cake.jpg",
        camel: p + "camel.jpg",
        candle: p + "candle.jpg",
        car: p + "car.jpg",
        carrot: p + "carrot.jpg",
        cat: p + "cat.jpg",
        cloud: p + "cloud.jpg",
        coffee: p + "coffee.jpg",
        cookie: p + "cookie.jpg",
        crayon: p + "crayon.jpg",
        dice: p + "dice.jpg",
        dinosaur: p + "dinosaur.jpg",
        doctor: p + "doctor.jpg",
        dog: p + "dog.jpg",
        dolphin: p + "dolphin.jpg",
        donkey: p + "donkey.jpg",
        donut: p + "donut.jpg",
        door: p + "door.jpg",
        drums: p + "drums.jpg",
        duck: p + "duck.jpg",
        feather: p + "feather.jpg",
        feet: p + "feet.jpg",
        fire: p + "fire.jpg",
        fish: p + "fish.jpg",
        flag: p + "flag.jpg",
        flamingo: p + "flamingo.jpg",
        flower: p + "flower.jpg",
        fork: p + "fork.jpg",
        fox: p + "fox.jpg",
        frog: p + "frog.jpg",
        giraffe: p + "giraffe.jpg",
        girl: p + "girl.jpg",
        glasses: p + "glasses.jpg",
        goat: p + "goat.jpg",
        goldfish: p + "goldfish.jpg",
        gong: p + "gong.jpg",
        gorilla: p + "gorilla.jpg",
        grapes: p + "grapes.jpg",
        grass: p + "grass.jpg",
        guitar: p + "guitar.jpg",
        hair: p + "hair.jpg",
        hammer: p + "hammer.jpg",
        hand: p + "hand.jpg",
        harp: p + "harp.jpg",
        hat: p + "hat.jpg",
        hedgehog: p + "hedgehog.jpg",
        helicopter: p + "helicopter.jpg",
        hippo: p + "hippo.jpg",
        horse: p + "horse.jpg",
        house: p + "house.jpg",
        ladder: p + "ladder.jpg",
        ladybug: p + "ladybug.jpg",
        lantern: p + "lantern.jpg",
        lavender: p + "lavender.jpg",
        leaf: p + "leaf.jpg",
        lemon: p + "lemon.jpg",
        leopard: p + "leopard.jpg",
        lime: p + "lime.jpg",
        lizard: p + "lizard.jpg",
        lychee: p + "lychee.jpg",
        marshmallow: p + "marshmallow.jpg",
        massage: p + "massage.jpg",
        match: p + "match.jpg",
        meerkat: p + "meerkat.jpg",
        microwave: p + "microwave.jpg",
        milk: p + "milk.jpg",
        money: p + "money.jpg",
        monkey: p + "monkey.jpg",
        mouse: p + "mouse.jpg",
        mushroom: p + "mushroom.jpg",
        paint: p + "paint.jpg",
        pelican: p + "pelican.jpg",
        pen: p + "pen.jpg",
        pencil: p + "pencil.jpg",
        penguin: p + "penguin.jpg",
        pigeon: p + "pigeon.jpg",
        pineapple: p + "pineapple.jpg",
        pizza: p + "pizza.jpg",
        plant: p + "plant.jpg",
        popcorn: p + "popcorn.jpg",
        shadow: p + "shadow.jpg",
        shark: p + "shark.jpg",
        sheep: p + "sheep.jpg",
        sheep2: p + "sheep2.jpg",
        shells: p + "shells.jpg",
        ship: p + "ship.jpg",
        shoe: p + "shoe.jpg",
        shoes: p + "shoes.jpg",
        shovel: p + "shovel.jpg",
        shower: p + "shower.jpg",
        tea: p + "tea.jpg",
        television: p + "television.jpg",
        tent: p + "tent.jpg",
        tiger: p + "tiger.jpg",
        toaster: p + "toaster.jpg",
        tomato: p + "tomato.jpg",
        train: p + "train.jpg",
        tree: p + "tree.jpg",
        turtle: p + "turtle.jpg",
        typewriter: p + "typewriter.jpg",
        vacuum: p + "vacuum.jpg",
        van: p + "van.jpg",
        vase: p + "vase.jpg",
        vegebles: p + "vegebles.jpg",
        vet: p + "vet.jpg",
        vine: p + "vine.jpg",
        violin: p + "violin.jpg",
        volcano: p + "volcano.jpg",
        volleyball: p + "volleyball.jpg",
        vulture: p + "vulture.jpg",
        waffle: p + "waffle.jpg",
        wallet: p + "wallet.jpg",
        walrus: p + "walrus.jpg",
        watch: p + "watch.jpg",
        water: p + "water.jpg",
        watermelon: p + "watermelon.jpg",
        whale: p + "whale.jpg",
        wheat: p + "wheat.jpg",
        window: p + "window.jpg",
        wolf: p + "wolf.jpg",
    },
    s = "audio/",
    sds = {
        swb: s + "ipa-sw-b.m4a",
        swc: s + "ipa-sw-c.m4a",
        swd: s + "ipa-sw-d.m4a",
        swf: s + "ipa-sw-f.m4a",
        swg: s + "ipa-sw-g.m4a",
        swh: s + "ipa-sw-h.m4a",
        swl: s + "ipa-sw-l.m4a",
        swm: s + "ipa-sw-m.m4a",
        swp: s + "ipa-sw-p.m4a",
        swsh: s + "ipa-sw-sh.m4a",
        swt: s + "ipa-sw-t.m4a",
        swv: s + "ipa-sw-v.m4a",
        sww: s + "ipa-sw-w.m4a",
    };
class Question {
    constructor(b, c, d, a, e) {
        (this.name = b),
            (this.text = c),
            (this.soundfile = d),
            (this.correctimage = a),
            (this.prompts = e),
            this.prompts.push(a);
    }
}
class SWQ extends Question {
    constructor(a, b, c, d) {
        super(
            a,
            "Please click the image that starts with this sound:",
            b,
            c,
            d
        );
    }
}
let qs = {
    b_0: new SWQ("Question 1", sds.swb, imgs.baby, [
        imgs.cookie,
        imgs.tea,
        imgs.whale,
    ]),
    b_1: new SWQ("Question 2", sds.swb, imgs.balloon, [
        imgs.tent,
        imgs.goat,
        imgs.car,
    ]),
    b_2: new SWQ("Question 3", sds.swb, imgs.banana, [
        imgs.sheep,
        imgs.gong,
        imgs.pizza,
    ]),
    b_3: new SWQ("Question 4", sds.swb, imgs.basket, [
        imgs.shoe,
        imgs.horse,
        imgs.toaster,
    ]),
    b_4: new SWQ("Question 5", sds.swb, imgs.bicycle, [
        imgs.leopard,
        imgs.hippo,
        imgs.typewriter,
    ]),
    b_5: new SWQ("Question 6", sds.swb, imgs.bird, [
        imgs.guitar,
        imgs.monkey,
        imgs.television,
    ]),
    b_6: new SWQ("Question 7", sds.swb, imgs.boat, [
        imgs.shells,
        imgs.gorilla,
        imgs.giraffe,
    ]),
    b_7: new SWQ("Question 8", sds.swb, imgs.bowl, [
        imgs.flag,
        imgs.donut,
        imgs.crayon,
    ]),
    b_8: new SWQ("Question 9", sds.swb, imgs.bread, [
        imgs.whale,
        imgs.frog,
        imgs.volcano,
    ]),
    b_9: new SWQ("Question 10", sds.swb, imgs.burger, [
        imgs.watermelon,
        imgs.popcorn,
        imgs.shoe,
    ]),
    c_0: new SWQ("Question 1", sds.swc, imgs.cake, [
        imgs.gorilla,
        imgs.hippo,
        imgs.goldfish,
    ]),
    c_1: new SWQ("Question 2", sds.swc, imgs.camel, [
        imgs.bicycle,
        imgs.fox,
        imgs.hammer,
    ]),
    c_2: new SWQ("Question 3", sds.swc, imgs.candle, [
        imgs.lantern,
        imgs.pen,
        imgs.hammer,
    ]),
    c_3: new SWQ("Question 4", sds.swc, imgs.car, [
        imgs.basket,
        imgs.leopard,
        imgs.baby,
    ]),
    c_4: new SWQ("Question 5", sds.swc, imgs.carrot, [
        imgs.lavender,
        imgs.shells,
        imgs.flower,
    ]),
    c_5: new SWQ("Question 6", sds.swc, imgs.cat, [
        imgs.fox,
        imgs.water,
        imgs.walrus,
    ]),
    c_6: new SWQ("Question 7", sds.swc, imgs.cloud, [
        imgs.feet,
        imgs.pizza,
        imgs.massage,
    ]),
    c_7: new SWQ("Question 8", sds.swc, imgs.coffee, [
        imgs.guitar,
        imgs.horse,
        imgs.hippo,
    ]),
    c_8: new SWQ("Question 9", sds.swc, imgs.cookie, [
        imgs.whale,
        imgs.feet,
        imgs.door,
    ]),
    c_9: new SWQ("Question 10", sds.swc, imgs.crayon, [
        imgs.ship,
        imgs.shoes,
        imgs.banana,
    ]),
    d_0: new SWQ("Question 1", sds.swd, imgs.dice, [
        imgs.baby,
        imgs.toaster,
        imgs.watermelon,
    ]),
    d_1: new SWQ("Question 2", sds.swd, imgs.dinosaur, [
        imgs.flag,
        imgs.violin,
        imgs.hedgehog,
    ]),
    d_2: new SWQ("Question 3", sds.swd, imgs.doctor, [
        imgs.helicopter,
        imgs.cookie,
        imgs.shoe,
    ]),
    d_3: new SWQ("Question 4", sds.swd, imgs.dog, [
        imgs.shark,
        imgs.basket,
        imgs.mushroom,
    ]),
    d_4: new SWQ("Question 5", sds.swd, imgs.dolphin, [
        imgs.shadow,
        imgs.hedgehog,
        imgs.hippo,
    ]),
    d_5: new SWQ("Question 6", sds.swd, imgs.donkey, [
        imgs.fish,
        imgs.cat,
        imgs.baby,
    ]),
    d_6: new SWQ("Question 7", sds.swd, imgs.donut, [
        imgs.hat,
        imgs.water,
        imgs.balloon,
    ]),
    d_7: new SWQ("Question 8", sds.swd, imgs.door, [
        imgs.mushroom,
        imgs.house,
        imgs.camel,
    ]),
    d_8: new SWQ("Question 9", sds.swd, imgs.drums, [
        imgs.grapes,
        imgs.hippo,
        imgs.hippo,
    ]),
    d_9: new SWQ("Question 10", sds.swd, imgs.duck, [
        imgs.lychee,
        imgs.glasses,
        imgs.shoes,
    ]),
    f_0: new SWQ("Question 1", sds.swf, imgs.feather, [
        imgs.monkey,
        imgs.watermelon,
        imgs.pelican,
    ]),
    f_1: new SWQ("Question 2", sds.swf, imgs.feet, [
        imgs.shells,
        imgs.mushroom,
        imgs.ladder,
    ]),
    f_2: new SWQ("Question 3", sds.swf, imgs.fire, [
        imgs.penguin,
        imgs.pigeon,
        imgs.pigeon,
    ]),
    f_3: new SWQ("Question 4", sds.swf, imgs.fish, [
        imgs.door,
        imgs.mouse,
        imgs.vulture,
    ]),
    f_4: new SWQ("Question 5", sds.swf, imgs.flag, [
        imgs.bicycle,
        imgs.donkey,
        imgs.banana,
    ]),
    f_5: new SWQ("Question 6", sds.swf, imgs.flamingo, [
        imgs.vine,
        imgs.shoes,
        imgs.vase,
    ]),
    f_6: new SWQ("Question 7", sds.swf, imgs.flower, [
        imgs.dinosaur,
        imgs.mushroom,
        imgs.coffee,
    ]),
    f_7: new SWQ("Question 8", sds.swf, imgs.fork, [
        imgs.wallet,
        imgs.sheep,
        imgs.baby,
    ]),
    f_8: new SWQ("Question 9", sds.swf, imgs.fox, [
        imgs.dice,
        imgs.duck,
        imgs.bowl,
    ]),
    f_9: new SWQ("Question 10", sds.swf, imgs.frog, [
        imgs.hippo,
        imgs.monkey,
        imgs.plant,
    ]),
    g_0: new SWQ("Question 1", sds.swg, imgs.giraffe, [
        imgs.volcano,
        imgs.bird,
        imgs.water,
    ]),
    g_1: new SWQ("Question 2", sds.swg, imgs.girl, [
        imgs.lychee,
        imgs.lantern,
        imgs.mushroom,
    ]),
    g_2: new SWQ("Question 3", sds.swg, imgs.glasses, [
        imgs.sheep,
        imgs.window,
        imgs.shadow,
    ]),
    g_3: new SWQ("Question 4", sds.swg, imgs.goat, [
        imgs.sheep,
        imgs.bowl,
        imgs.vine,
    ]),
    g_4: new SWQ("Question 5", sds.swg, imgs.goldfish, [
        imgs.toaster,
        imgs.ladybug,
        imgs.lemon,
    ]),
    g_5: new SWQ("Question 6", sds.swg, imgs.gong, [
        imgs.basket,
        imgs.harp,
        imgs.fork,
    ]),
    g_6: new SWQ("Question 7", sds.swg, imgs.gorilla, [
        imgs.bicycle,
        imgs.marshmallow,
        imgs.meerkat,
    ]),
    g_7: new SWQ("Question 8", sds.swg, imgs.grapes, [
        imgs.lime,
        imgs.vegebles,
        imgs.flamingo,
    ]),
    g_8: new SWQ("Question 9", sds.swg, imgs.grass, [
        imgs.ladybug,
        imgs.shells,
        imgs.cookie,
    ]),
    g_9: new SWQ("Question 10", sds.swg, imgs.guitar, [
        imgs.plant,
        imgs.monkey,
        imgs.paint,
    ]),
    h_0: new SWQ("Question 1", sds.swh, imgs.hair, [
        imgs.doctor,
        imgs.flower,
        imgs.glasses,
    ]),
    h_1: new SWQ("Question 2", sds.swh, imgs.hammer, [
        imgs.volleyball,
        imgs.shoe,
        imgs.turtle,
    ]),
    h_2: new SWQ("Question 3", sds.swh, imgs.hand, [
        imgs.dog,
        imgs.flamingo,
        imgs.violin,
    ]),
    h_3: new SWQ("Question 4", sds.swh, imgs.harp, [
        imgs.shoe,
        imgs.leopard,
        imgs.volcano,
    ]),
    h_4: new SWQ("Question 5", sds.swh, imgs.hat, [
        imgs.lime,
        imgs.goldfish,
        imgs.leaf,
    ]),
    h_5: new SWQ("Question 6", sds.swh, imgs.hedgehog, [
        imgs.banana,
        imgs.vase,
        imgs.vase,
    ]),
    h_6: new SWQ("Question 7", sds.swh, imgs.helicopter, [
        imgs.paint,
        imgs.goldfish,
        imgs.grass,
    ]),
    h_7: new SWQ("Question 8", sds.swh, imgs.hippo, [
        imgs.pineapple,
        imgs.flamingo,
        imgs.watch,
    ]),
    h_8: new SWQ("Question 9", sds.swh, imgs.horse, [
        imgs.train,
        imgs.banana,
        imgs.sheep,
    ]),
    h_9: new SWQ("Question 10", sds.swh, imgs.house, [
        imgs.television,
        imgs.pencil,
        imgs.ship,
    ]),
    l_0: new SWQ("Question 1", sds.swl, imgs.ladder, [
        imgs.feet,
        imgs.train,
        imgs.drums,
    ]),
    l_1: new SWQ("Question 2", sds.swl, imgs.ladybug, [
        imgs.water,
        imgs.toaster,
        imgs.whale,
    ]),
    l_2: new SWQ("Question 3", sds.swl, imgs.lantern, [
        imgs.turtle,
        imgs.grapes,
        imgs.wolf,
    ]),
    l_3: new SWQ("Question 4", sds.swl, imgs.lavender, [
        imgs.typewriter,
        imgs.bicycle,
        imgs.van,
    ]),
    l_4: new SWQ("Question 5", sds.swl, imgs.leaf, [
        imgs.shoe,
        imgs.shells,
        imgs.donkey,
    ]),
    l_5: new SWQ("Question 6", sds.swl, imgs.lemon, [
        imgs.goldfish,
        imgs.candle,
        imgs.sheep,
    ]),
    l_6: new SWQ("Question 7", sds.swl, imgs.leopard, [
        imgs.bowl,
        imgs.pelican,
        imgs.goldfish,
    ]),
    l_7: new SWQ("Question 8", sds.swl, imgs.lime, [
        imgs.microwave,
        imgs.shovel,
        imgs.cat,
    ]),
    l_8: new SWQ("Question 9", sds.swl, imgs.lizard, [
        imgs.money,
        imgs.gorilla,
        imgs.hat,
    ]),
    l_9: new SWQ("Question 10", sds.swl, imgs.lychee, [
        imgs.hippo,
        imgs.vegebles,
        imgs.basket,
    ]),
    m_0: new SWQ("Question 1", sds.swm, imgs.marshmallow, [
        imgs.car,
        imgs.violin,
        imgs.horse,
    ]),
    m_1: new SWQ("Question 2", sds.swm, imgs.massage, [
        imgs.lavender,
        imgs.carrot,
        imgs.flamingo,
    ]),
    m_2: new SWQ("Question 3", sds.swm, imgs.match, [
        imgs.duck,
        imgs.fox,
        imgs.lime,
    ]),
    m_3: new SWQ("Question 4", sds.swm, imgs.meerkat, [
        imgs.pen,
        imgs.giraffe,
        imgs.lizard,
    ]),
    m_4: new SWQ("Question 5", sds.swm, imgs.microwave, [
        imgs.dinosaur,
        imgs.pencil,
        imgs.dog,
    ]),
    m_5: new SWQ("Question 6", sds.swm, imgs.milk, [
        imgs.tiger,
        imgs.glasses,
        imgs.ladybug,
    ]),
    m_6: new SWQ("Question 7", sds.swm, imgs.money, [
        imgs.cookie,
        imgs.glasses,
        imgs.pizza,
    ]),
    m_7: new SWQ("Question 8", sds.swm, imgs.monkey, [
        imgs.tea,
        imgs.popcorn,
        imgs.pelican,
    ]),
    m_8: new SWQ("Question 9", sds.swm, imgs.mouse, [
        imgs.cake,
        imgs.tree,
        imgs.waffle,
    ]),
    m_9: new SWQ("Question 10", sds.swm, imgs.mushroom, [
        imgs.door,
        imgs.camel,
        imgs.ship,
    ]),
    p_0: new SWQ("Question 1", sds.swp, imgs.paint, [
        imgs.burger,
        imgs.walrus,
        imgs.shark,
    ]),
    p_1: new SWQ("Question 2", sds.swp, imgs.pelican, [
        imgs.harp,
        imgs.cookie,
        imgs.guitar,
    ]),
    p_2: new SWQ("Question 3", sds.swp, imgs.pen, [
        imgs.typewriter,
        imgs.dog,
        imgs.fork,
    ]),
    p_3: new SWQ("Question 4", sds.swp, imgs.pencil, [
        imgs.balloon,
        imgs.flower,
        imgs.bicycle,
    ]),
    p_4: new SWQ("Question 5", sds.swp, imgs.penguin, [
        imgs.door,
        imgs.hippo,
        imgs.massage,
    ]),
    p_5: new SWQ("Question 6", sds.swp, imgs.pigeon, [
        imgs.typewriter,
        imgs.hair,
        imgs.tea,
    ]),
    p_6: new SWQ("Question 7", sds.swp, imgs.pineapple, [
        imgs.duck,
        imgs.leopard,
        imgs.ladybug,
    ]),
    p_7: new SWQ("Question 8", sds.swp, imgs.pizza, [
        imgs.van,
        imgs.dog,
        imgs.helicopter,
    ]),
    p_8: new SWQ("Question 9", sds.swp, imgs.plant, [
        imgs.van,
        imgs.turtle,
        imgs.lizard,
    ]),
    p_9: new SWQ("Question 10", sds.swp, imgs.popcorn, [
        imgs.walrus,
        imgs.mushroom,
        imgs.typewriter,
    ]),
    sh_0: new SWQ("Question 1", sds.swsh, imgs.shadow, [
        imgs.goat,
        imgs.giraffe,
        imgs.waffle,
    ]),
    sh_1: new SWQ("Question 2", sds.swsh, imgs.shark, [
        imgs.money,
        imgs.boat,
        imgs.lychee,
    ]),
    sh_2: new SWQ("Question 3", sds.swsh, imgs.sheep, [
        imgs.feather,
        imgs.duck,
        imgs.popcorn,
    ]),
    sh_3: new SWQ("Question 4", sds.swsh, imgs.sheep2, [
        imgs.feet,
        imgs.wolf,
        imgs.monkey,
    ]),
    sh_4: new SWQ("Question 5", sds.swsh, imgs.shells, [
        imgs.cloud,
        imgs.cookie,
        imgs.crayon,
    ]),
    sh_5: new SWQ("Question 6", sds.swsh, imgs.ship, [
        imgs.dog,
        imgs.crayon,
        imgs.horse,
    ]),
    sh_6: new SWQ("Question 7", sds.swsh, imgs.shoe, [
        imgs.lantern,
        imgs.vegebles,
        imgs.penguin,
    ]),
    sh_7: new SWQ("Question 8", sds.swsh, imgs.shoes, [
        imgs.grapes,
        imgs.leopard,
        imgs.pineapple,
    ]),
    sh_8: new SWQ("Question 9", sds.swsh, imgs.shovel, [
        imgs.fork,
        imgs.turtle,
        imgs.massage,
    ]),
    sh_9: new SWQ("Question 10", sds.swsh, imgs.shower, [
        imgs.drums,
        imgs.vase,
        imgs.paint,
    ]),
    t_0: new SWQ("Question 1", sds.swt, imgs.tea, [
        imgs.house,
        imgs.plant,
        imgs.shadow,
    ]),
    t_1: new SWQ("Question 2", sds.swt, imgs.television, [
        imgs.watch,
        imgs.pizza,
        imgs.van,
    ]),
    t_2: new SWQ("Question 3", sds.swt, imgs.tent, [
        imgs.basket,
        imgs.waffle,
        imgs.house,
    ]),
    t_3: new SWQ("Question 4", sds.swt, imgs.tiger, [
        imgs.pigeon,
        imgs.pelican,
        imgs.violin,
    ]),
    t_4: new SWQ("Question 5", sds.swt, imgs.toaster, [
        imgs.duck,
        imgs.lychee,
        imgs.monkey,
    ]),
    t_5: new SWQ("Question 6", sds.swt, imgs.tomato, [
        imgs.hat,
        imgs.gong,
        imgs.drums,
    ]),
    t_6: new SWQ("Question 7", sds.swt, imgs.train, [
        imgs.lime,
        imgs.lizard,
        imgs.donut,
    ]),
    t_7: new SWQ("Question 8", sds.swt, imgs.tree, [
        imgs.pigeon,
        imgs.microwave,
        imgs.water,
    ]),
    t_8: new SWQ("Question 9", sds.swt, imgs.turtle, [
        imgs.pen,
        imgs.vulture,
        imgs.van,
    ]),
    t_9: new SWQ("Question 10", sds.swt, imgs.typewriter, [
        imgs.bird,
        imgs.door,
        imgs.microwave,
    ]),
    v_0: new SWQ("Question 1", sds.swv, imgs.vacuum, [
        imgs.boat,
        imgs.bicycle,
        imgs.train,
    ]),
    v_1: new SWQ("Question 2", sds.swv, imgs.van, [
        imgs.hair,
        imgs.pelican,
        imgs.shower,
    ]),
    v_2: new SWQ("Question 3", sds.swv, imgs.vase, [
        imgs.water,
        imgs.fork,
        imgs.tomato,
    ]),
    v_3: new SWQ("Question 4", sds.swv, imgs.vegebles, [
        imgs.train,
        imgs.television,
        imgs.match,
    ]),
    v_4: new SWQ("Question 5", sds.swv, imgs.vet, [
        imgs.feet,
        imgs.donkey,
        imgs.harp,
    ]),
    v_5: new SWQ("Question 6", sds.swv, imgs.vine, [
        imgs.monkey,
        imgs.sheep,
        imgs.feather,
    ]),
    v_6: new SWQ("Question 7", sds.swv, imgs.violin, [
        imgs.shark,
        imgs.hand,
        imgs.walrus,
    ]),
    v_7: new SWQ("Question 8", sds.swv, imgs.volcano, [
        imgs.dice,
        imgs.match,
        imgs.boat,
    ]),
    v_8: new SWQ("Question 9", sds.swv, imgs.volleyball, [
        imgs.coffee,
        imgs.paint,
        imgs.match,
    ]),
    v_9: new SWQ("Question 10", sds.swv, imgs.vulture, [
        imgs.lizard,
        imgs.hat,
        imgs.balloon,
    ]),
    w_0: new SWQ("Question 1", sds.sww, imgs.waffle, [
        imgs.shoe,
        imgs.marshmallow,
        imgs.fox,
    ]),
    w_1: new SWQ("Question 2", sds.sww, imgs.wallet, [
        imgs.pen,
        imgs.plant,
        imgs.cloud,
    ]),
    w_2: new SWQ("Question 3", sds.sww, imgs.walrus, [
        imgs.lemon,
        imgs.ship,
        imgs.donkey,
    ]),
    w_3: new SWQ("Question 4", sds.sww, imgs.watch, [
        imgs.doctor,
        imgs.dog,
        imgs.cat,
    ]),
    w_4: new SWQ("Question 5", sds.sww, imgs.water, [
        imgs.gorilla,
        imgs.donut,
        imgs.microwave,
    ]),
    w_5: new SWQ("Question 6", sds.sww, imgs.watermelon, [
        imgs.mouse,
        imgs.grapes,
        imgs.gong,
    ]),
    w_6: new SWQ("Question 7", sds.sww, imgs.whale, [
        imgs.volcano,
        imgs.grapes,
        imgs.shovel,
    ]),
    w_7: new SWQ("Question 8", sds.sww, imgs.wheat, [
        imgs.doctor,
        imgs.bowl,
        imgs.hand,
    ]),
    w_8: new SWQ("Question 9", sds.sww, imgs.window, [
        imgs.mushroom,
        imgs.pelican,
        imgs.camel,
    ]),
    w_9: new SWQ("Question 10", sds.sww, imgs.wolf, [
        imgs.shovel,
        imgs.giraffe,
        imgs.frog,
    ]),
};
class QS {
    constructor(a, b) {
        (this.name = a), (this.qs = b);
    }
}
let sets = {
    b: new QS("Set 1", [
        qs.b_0,
        qs.b_1,
        qs.b_2,
        qs.b_3,
        qs.b_4,
        qs.b_5,
        qs.b_6,
        qs.b_7,
        qs.b_8,
        qs.b_9,
    ]),
    c: new QS("Set 2", [
        qs.c_0,
        qs.c_1,
        qs.c_2,
        qs.c_3,
        qs.c_4,
        qs.c_5,
        qs.c_6,
        qs.c_7,
        qs.c_8,
        qs.c_9,
    ]),
    d: new QS("Set 3", [
        qs.d_0,
        qs.d_1,
        qs.d_2,
        qs.d_3,
        qs.d_4,
        qs.d_5,
        qs.d_6,
        qs.d_7,
        qs.d_8,
        qs.d_9,
    ]),
    f: new QS("Set 4", [
        qs.f_0,
        qs.f_1,
        qs.f_2,
        qs.f_3,
        qs.f_4,
        qs.f_5,
        qs.f_6,
        qs.f_7,
        qs.f_8,
        qs.f_9,
    ]),
    g: new QS("Set 5", [
        qs.g_0,
        qs.g_1,
        qs.g_2,
        qs.g_3,
        qs.g_4,
        qs.g_5,
        qs.g_6,
        qs.g_7,
        qs.g_8,
        qs.g_9,
    ]),
    h: new QS("Set 6", [
        qs.h_0,
        qs.h_1,
        qs.h_2,
        qs.h_3,
        qs.h_4,
        qs.h_5,
        qs.h_6,
        qs.h_7,
        qs.h_8,
        qs.h_9,
    ]),
    l: new QS("Set 7", [
        qs.l_0,
        qs.l_1,
        qs.l_2,
        qs.l_3,
        qs.l_4,
        qs.l_5,
        qs.l_6,
        qs.l_7,
        qs.l_8,
        qs.l_9,
    ]),
    m: new QS("Set 8", [
        qs.m_0,
        qs.m_1,
        qs.m_2,
        qs.m_3,
        qs.m_4,
        qs.m_5,
        qs.m_6,
        qs.m_7,
        qs.m_8,
        qs.m_9,
    ]),
    p: new QS("Set 9", [
        qs.p_0,
        qs.p_1,
        qs.p_2,
        qs.p_3,
        qs.p_4,
        qs.p_5,
        qs.p_6,
        qs.p_7,
        qs.p_8,
        qs.p_9,
    ]),
    sh: new QS("Set 10", [
        qs.sh_0,
        qs.sh_1,
        qs.sh_2,
        qs.sh_3,
        qs.sh_4,
        qs.sh_5,
        qs.sh_6,
        qs.sh_7,
        qs.sh_8,
        qs.sh_9,
    ]),
    t: new QS("Set 11", [
        qs.t_0,
        qs.t_1,
        qs.t_2,
        qs.t_3,
        qs.t_4,
        qs.t_5,
        qs.t_6,
        qs.t_7,
        qs.t_8,
        qs.t_9,
    ]),
    v: new QS("Set 12", [
        qs.v_0,
        qs.v_1,
        qs.v_2,
        qs.v_3,
        qs.v_4,
        qs.v_5,
        qs.v_6,
        qs.v_7,
        qs.v_8,
        qs.v_9,
    ]),
    w: new QS("Set 13", [
        qs.w_0,
        qs.w_1,
        qs.w_2,
        qs.w_3,
        qs.w_4,
        qs.w_5,
        qs.w_6,
        qs.w_7,
        qs.w_8,
        qs.w_9,
    ]),
};
class Activity {
    constructor(a, b, c) {
        (this.name = a), (this.abbr = b), (this.sets = c);
    }
}
export const activities = {
    ipa: new Activity("Implicit Phoneme Manipulation", "IPM", [
        sets.b,
        sets.c,
        sets.d,
        sets.f,
        sets.g,
        sets.h,
        sets.l,
        sets.m,
        sets.p,
        sets.sh,
        sets.t,
        sets.v,
        sets.w,
    ]),
    pca: new Activity("Phonological Component Analysis", "PCA", [sets.b]),
};
