const p = "images/image prompts/"; //image path
const images = {
    //iamges
    baby: p + "baby.jpg",
    balloon: p + "balloon.jpg",
    banana: p + "banana.jpg",
    basket: p + "basket.jpg",
    bicycle: p + "bicycle.jpg",
    bird: p + "bird.jpg",
    boat: p + "boat.jpg",
    bowl: p + "bowl.jpg",
    bread: p + "bread.jpg",
    burger: p + "burger.jpg",
    cake: p + "cake.jpg",
    camel: p + "camel.jpg",
    candle: p + "candle.jpg",
    car: p + "car.jpg",
    carrot: p + "carrot.jpg",
    cat: p + "cat.jpg",
    cloud: p + "cloud.jpg",
    coffee: p + "coffee.jpg",
    cookie: p + "cookie.jpg",
    crayon: p + "crayon.jpg",
    dice: p + "dice.jpg",
    dinosaur: p + "dinosaur.jpg",
    doctor: p + "doctor.jpg",
    dog: p + "dog.jpg",
    dolphin: p + "dolphin.jpg",
    donkey: p + "donkey.jpg",
    donut: p + "donut.jpg",
    door: p + "door.jpg",
    drums: p + "drums.jpg",
    duck: p + "duck.jpg",
    feather: p + "feather.jpg",
    feet: p + "feet.jpg",
    fire: p + "fire.jpg",
    fish: p + "fish.jpg",
    flag: p + "flag.jpg",
    flamingo: p + "flamingo.jpg",
    flower: p + "flower.jpg",
    fork: p + "fork.jpg",
    fox: p + "fox.jpg",
    frog: p + "frog.jpg",
    giraffe: p + "giraffe.jpg",
    girl: p + "girl.jpg",
    glasses: p + "glasses.jpg",
    goat: p + "goat.jpg",
    goldfish: p + "goldfish.jpg",
    gong: p + "gong.jpg",
    gorilla: p + "gorilla.jpg",
    grapes: p + "grapes.jpg",
    grass: p + "grass.jpg",
    guitar: p + "guitar.jpg",
    hair: p + "hair.jpg",
    hammer: p + "hammer.jpg",
    hand: p + "hand.jpg",
    harp: p + "harp.jpg",
    hat: p + "hat.jpg",
    hedgehog: p + "hedgehog.jpg",
    helicopter: p + "helicopter.jpg",
    hippo: p + "hippo.jpg",
    horse: p + "horse.jpg",
    house: p + "house.jpg",
    ladder: p + "ladder.jpg",
    ladybug: p + "ladybug.jpg",
    lantern: p + "lantern.jpg",
    lavender: p + "lavender.jpg",
    leaf: p + "leaf.jpg",
    lemon: p + "lemon.jpg",
    leopard: p + "leopard.jpg",
    lime: p + "lime.jpg",
    lizard: p + "lizard.jpg",
    lychee: p + "lychee.jpg",
    marshmallow: p + "marshmallow.jpg",
    massage: p + "massage.jpg",
    match: p + "match.jpg",
    meerkat: p + "meerkat.jpg",
    microwave: p + "microwave.jpg",
    milk: p + "milk.jpg",
    money: p + "money.jpg",
    monkey: p + "monkey.jpg",
    mouse: p + "mouse.jpg",
    mushroom: p + "mushroom.jpg",
    paint: p + "paint.jpg",
    pelican: p + "pelican.jpg",
    pen: p + "pen.jpg",
    pencil: p + "pencil.jpg",
    penguin: p + "penguin.jpg",
    pigeon: p + "pigeon.jpg",
    pineapple: p + "pineapple.jpg",
    pizza: p + "pizza.jpg",
    plant: p + "plant.jpg",
    popcorn: p + "popcorn.jpg",
    shadow: p + "shadow.jpg",
    shark: p + "shark.jpg",
    sheep: p + "sheep.jpg",
    sheep2: p + "sheep2.jpg",
    shells: p + "shells.jpg",
    ship: p + "ship.jpg",
    shoe: p + "shoe.jpg",
    shoes: p + "shoes.jpg",
    shovel: p + "shovel.jpg",
    shower: p + "shower.jpg",
    tea: p + "tea.jpg",
    television: p + "television.jpg",
    tent: p + "tent.jpg",
    tiger: p + "tiger.jpg",
    toaster: p + "toaster.jpg",
    tomato: p + "tomato.jpg",
    train: p + "train.jpg",
    tree: p + "tree.jpg",
    turtle: p + "turtle.jpg",
    typewriter: p + "typewriter.jpg",
    vacuum: p + "vacuum.jpg",
    van: p + "van.jpg",
    vase: p + "vase.jpg",
    vegebles: p + "vegebles.jpg",
    vet: p + "vet.jpg",
    vine: p + "vine.jpg",
    violin: p + "violin.jpg",
    volcano: p + "volcano.jpg",
    volleyball: p + "volleyball.jpg",
    vulture: p + "vulture.jpg",
    waffle: p + "waffle.jpg",
    wallet: p + "wallet.jpg",
    walrus: p + "walrus.jpg",
    watch: p + "watch.jpg",
    water: p + "water.jpg",
    watermelon: p + "watermelon.jpg",
    whale: p + "whale.jpg",
    wheat: p + "wheat.jpg",
    window: p + "window.jpg",
    wolf: p + "wolf.jpg",
};

class Question {
    constructor(text, soundfile, correctimage, redherrings) {
        this.text = text;
        this.soundfile = soundfile;
        this.correctimage = correctimage;
        this.prompts = redherrings;
        this.prompts.push(correctimage);
    }
}

class SWQ extends Question {
    //Starts with question
    constructor(soundfile, correctimage, redherrings) {
        super(
            "Please click the image that starts with this sound:",
            soundfile,
            correctimage,
            redherrings
        );
    }
}

const questions = {
    b_0: new SWQ("", images.baby, [images.cookie, images.pelican, images.van]),
    b_1: new SWQ("", images.balloon, [images.tent, images.goat, images.car]),
    b_2: new SWQ("", images.banana, [images.sheep, images.gong, images.pizza]),
    b_3: new SWQ("", images.basket, [images.shoe, images.horse, images.toaster]),
    b_4: new SWQ("", images.bicycle, [images.leopard, images.hippo, images.typewriter]),
    b_5: new SWQ("", images.bird, [images.guitar, images.monkey, images.television]),
    b_6: new SWQ("", images.boat, [images.shells, images.gorilla, images.giraffe]),
    b_7: new SWQ("", images.bowl, [images.hair, images.donut, images.crayon]),
    b_8: new SWQ("", images.bread, [images.whale, images.frog, images.volcano]),
    b_9: new SWQ("", images.burger, [images.watermelon, images.popcorn, images.shoe]),
    c_0: new SWQ("", images.cake, [images.gorilla, images.hippo, images.goldfish]),
    c_1: new SWQ("", images.camel, [images.bicycle, images.fox, images.hammer]),
    c_2: new SWQ("", images.candle, [images.lantern, images.pen, images.hammer]),
    c_3: new SWQ("", images.car, [images.basket, images.leopard, images.baby]),
    c_4: new SWQ("", images.carrot, [images.lavender, images.shells, images.flower]),
    c_5: new SWQ("", images.cat, [images.fox, images.water, images.walrus]),
    c_6: new SWQ("", images.cloud, [images.feet, images.pizza, images.massage]),
    c_7: new SWQ("", images.coffee, [images.guitar, images.horse, images.hippo]),
    c_8: new SWQ("", images.cookie, [images.whale, images.whale, images.door]),
    c_9: new SWQ("", images.crayon, [images.ship, images.shoes, images.banana]),
    d_0: new SWQ("", images.dice, [images.baby, images.toaster, images.watermelon]),
    d_1: new SWQ("", images.dinosaur, [images.flag, images.violin, images.hedgehog]),
    d_2: new SWQ("", images.doctor, [images.helicopter, images.cookie, images.shoe]),
    d_3: new SWQ("", images.dog, [images.shark, images.basket, images.mushroom]),
    d_4: new SWQ("", images.dolphin, [images.shadow, images.hedgehog, images.hippo]),
    d_5: new SWQ("", images.donkey, [images.fish, images.cat, images.baby]),
    d_6: new SWQ("", images.donut, [images.hat, images.water, images.balloon]),
    d_7: new SWQ("", images.door, [images.mushroom, images.house, images.camel]),
    d_8: new SWQ("", images.drums, [images.grapes, images.hippo, images.hippo]),
    d_9: new SWQ("", images.duck, [images.lychee, images.glasses, images.shoes]),
    f_0: new SWQ("", images.feather, [images.monkey, images.watermelon, images.pelican]),
    f_1: new SWQ("", images.feet, [images.shells, images.mushroom, images.ladder]),
    f_2: new SWQ("", images.fire, [images.penguin, images.pigeon, images.pigeon]),
    f_3: new SWQ("", images.fish, [images.door, images.mouse, images.vulture]),
    f_4: new SWQ("", images.flag, [images.bicycle, images.donkey, images.banana]),
    f_5: new SWQ("", images.flamingo, [images.vine, images.shoes, images.vase]),
    f_6: new SWQ("", images.flower, [images.dinosaur, images.mushroom, images.coffee]),
    f_7: new SWQ("", images.fork, [images.wallet, images.sheep, images.baby]),
    f_8: new SWQ("", images.fox, [images.dice, images.duck, images.bowl]),
    f_9: new SWQ("", images.frog, [images.hippo, images.monkey, images.plant]),
    g_0: new SWQ("", images.giraffe, [images.volcano, images.bird, images.water]),
    g_1: new SWQ("", images.girl, [images.lychee, images.lantern, images.mushroom]),
    g_2: new SWQ("", images.glasses, [images.sheep, images.window, images.shadow]),
    g_3: new SWQ("", images.goat, [images.sheep, images.bowl, images.vine]),
    g_4: new SWQ("", images.goldfish, [images.toaster, images.ladybug, images.lemon]),
    g_5: new SWQ("", images.gong, [images.basket, images.harp, images.fork]),
    g_6: new SWQ("", images.gorilla, [images.bicycle, images.marshmallow, images.meerkat]),
    g_7: new SWQ("", images.grapes, [images.lime, images.vegebles, images.flamingo]),
    g_8: new SWQ("", images.grass, [images.ladybug, images.shells, images.cookie]),
    g_9: new SWQ("", images.guitar, [images.plant, images.monkey, images.paint]),
    h_0: new SWQ("", images.hair, [images.doctor, images.flower, images.glasses]),
    h_1: new SWQ("", images.hammer, [images.volleyball, images.shoe, images.turtle]),
    h_2: new SWQ("", images.hand, [images.dog, images.flamingo, images.violin]),
    h_3: new SWQ("", images.harp, [images.shoe, images.leopard, images.volcano]),
    h_4: new SWQ("", images.hat, [images.lime, images.goldfish, images.leaf]),
    h_5: new SWQ("", images.hedgehog, [images.banana, images.vase, images.vase]),
    h_6: new SWQ("", images.helicopter, [images.paint, images.goldfish, images.grass]),
    h_7: new SWQ("", images.hippo, [images.pineapple, images.flamingo, images.watch]),
    h_8: new SWQ("", images.horse, [images.train, images.banana, images.sheep]),
    h_9: new SWQ("", images.house, [images.television, images.pencil, images.ship]),
    l_0: new SWQ("", images.ladder, [images.feet, images.train, images.drums]),
    l_1: new SWQ("", images.ladybug, [images.water, images.toaster, images.whale]),
    l_2: new SWQ("", images.lantern, [images.turtle, images.grapes, images.wolf]),
    l_3: new SWQ("", images.lavender, [images.typewriter, images.bicycle, images.van]),
    l_4: new SWQ("", images.leaf, [images.shoe, images.shells, images.donkey]),
    l_5: new SWQ("", images.lemon, [images.goldfish, images.candle, images.sheep]),
    l_6: new SWQ("", images.leopard, [images.bowl, images.pelican, images.goldfish]),
    l_7: new SWQ("", images.lime, [images.microwave, images.shovel, images.cat]),
    l_8: new SWQ("", images.lizard, [images.money, images.gorilla, images.hat]),
    l_9: new SWQ("", images.lychee, [images.hippo, images.vegebles, images.basket]),
    m_0: new SWQ("", images.marshmallow, [images.car, images.violin, images.horse]),
    m_1: new SWQ("", images.massage, [images.lavender, images.carrot, images.flamingo]),
    m_2: new SWQ("", images.match, [images.duck, images.fox, images.lime]),
    m_3: new SWQ("", images.meerkat, [images.pen, images.giraffe, images.lizard]),
    m_4: new SWQ("", images.microwave, [images.dinosaur, images.pencil, images.dog]),
    m_5: new SWQ("", images.milk, [images.tiger, images.glasses, images.ladybug]),
    m_6: new SWQ("", images.money, [images.cookie, images.glasses, images.pizza]),
    m_7: new SWQ("", images.monkey, [images.tea, images.popcorn, images.pelican]),
    m_8: new SWQ("", images.mouse, [images.cake, images.tree, images.waffle]),
    m_9: new SWQ("", images.mushroom, [images.door, images.camel, images.ship]),
    p_0: new SWQ("", images.paint, [images.burger, images.walrus, images.shark]),
    p_1: new SWQ("", images.pelican, [images.harp, images.cookie, images.guitar]),
    p_2: new SWQ("", images.pen, [images.typewriter, images.dog, images.fork]),
    p_3: new SWQ("", images.pencil, [images.balloon, images.flower, images.bicycle]),
    p_4: new SWQ("", images.penguin, [images.door, images.hippo, images.massage]),
    p_5: new SWQ("", images.pigeon, [images.typewriter, images.hair, images.tea]),
    p_6: new SWQ("", images.pineapple, [images.duck, images.leopard, images.ladybug]),
    p_7: new SWQ("", images.pizza, [images.van, images.dog, images.helicopter]),
    p_8: new SWQ("", images.plant, [images.van, images.turtle, images.lizard]),
    p_9: new SWQ("", images.popcorn, [images.walrus, images.mushroom, images.typewriter]),
    sh_0: new SWQ("", images.shadow, [images.goat, images.giraffe, images.waffle]),
    sh_1: new SWQ("", images.shark, [images.money, images.boat, images.lychee]),
    sh_2: new SWQ("", images.sheep, [images.feather, images.duck, images.popcorn]),
    sh_3: new SWQ("", images.sheep2, [images.feet, images.wolf, images.monkey]),
    sh_4: new SWQ("", images.shells, [images.cloud, images.cookie, images.crayon]),
    sh_5: new SWQ("", images.ship, [images.dog, images.crayon, images.horse]),
    sh_6: new SWQ("", images.shoe, [images.lantern, images.vegebles, images.penguin]),
    sh_7: new SWQ("", images.shoes, [images.grapes, images.leopard, images.pineapple]),
    sh_8: new SWQ("", images.shovel, [images.fork, images.turtle, images.massage]),
    sh_9: new SWQ("", images.shower, [images.drums, images.vase, images.paint]),
    t_0: new SWQ("", images.tea, [images.house, images.plant, images.shadow]),
    t_1: new SWQ("", images.television, [images.watch, images.pizza, images.van]),
    t_2: new SWQ("", images.tent, [images.basket, images.waffle, images.house]),
    t_3: new SWQ("", images.tiger, [images.pigeon, images.pelican, images.violin]),
    t_4: new SWQ("", images.toaster, [images.duck, images.lychee, images.monkey]),
    t_5: new SWQ("", images.tomato, [images.hat, images.gong, images.drums]),
    t_6: new SWQ("", images.train, [images.lime, images.lime, images.donut]),
    t_7: new SWQ("", images.tree, [images.pigeon, images.microwave, images.water]),
    t_8: new SWQ("", images.turtle, [images.pen, images.vulture, images.van]),
    t_9: new SWQ("", images.typewriter, [images.bird, images.door, images.microwave]),
    v_0: new SWQ("", images.vacuum, [images.boat, images.bicycle, images.train]),
    v_1: new SWQ("", images.van, [images.hair, images.pelican, images.shower]),
    v_2: new SWQ("", images.vase, [images.water, images.fork, images.tomato]),
    v_3: new SWQ("", images.vegebles, [images.train, images.television, images.match]),
    v_4: new SWQ("", images.vet, [images.feet, images.donkey, images.harp]),
    v_5: new SWQ("", images.vine, [images.monkey, images.sheep, images.feather]),
    v_6: new SWQ("", images.violin, [images.shark, images.hand, images.walrus]),
    v_7: new SWQ("", images.volcano, [images.dice, images.match, images.boat]),
    v_8: new SWQ("", images.volleyball, [images.coffee, images.paint, images.match]),
    v_9: new SWQ("", images.vulture, [images.lizard, images.hat, images.balloon]),
    w_0: new SWQ("", images.waffle, [images.shoe, images.marshmallow, images.fox]),
    w_1: new SWQ("", images.wallet, [images.pen, images.plant, images.cloud]),
    w_2: new SWQ("", images.walrus, [images.lemon, images.ship, images.donkey]),
    w_3: new SWQ("", images.watch, [images.doctor, images.dog, images.cat]),
    w_4: new SWQ("", images.water, [images.gorilla, images.donut, images.microwave]),
    w_5: new SWQ("", images.watermelon, [images.mouse, images.grapes, images.gong]),
    w_6: new SWQ("", images.whale, [images.volcano, images.grapes, images.shovel]),
    w_7: new SWQ("", images.wheat, [images.doctor, images.bowl, images.hand]),
    w_8: new SWQ("", images.window, [images.mushroom, images.pelican, images.camel]),
    w_9: new SWQ("", images.wolf, [images.shovel, images.giraffe, images.frog]),
};

class QS {
    //questionset
    constructor(name, questions) {
        this.name = name;
        this.activities = questions;
    }
}

const sets = {
    //question sets
    b: new QS("Set 1", [
        questions.b_0,
        questions.b_1,
        questions.b_2,
        questions.b_3,
        questions.b_4,
        questions.b_5,
        questions.b_6,
        questions.b_7,
        questions.b_8,
        questions.b_9,
    ]),
    c: new QS("Set 2", [
        questions.c_0,
        questions.c_1,
        questions.c_2,
        questions.c_3,
        questions.c_4,
        questions.c_5,
        questions.c_6,
        questions.c_7,
        questions.c_8,
        questions.c_9,
    ]),
    d: new QS("Set 3", [
        questions.d_0,
        questions.d_1,
        questions.d_2,
        questions.d_3,
        questions.d_4,
        questions.d_5,
        questions.d_6,
        questions.d_7,
        questions.d_8,
        questions.d_9,
    ]),
    f: new QS("Set 4", [
        questions.f_0,
        questions.f_1,
        questions.f_2,
        questions.f_3,
        questions.f_4,
        questions.f_5,
        questions.f_6,
        questions.f_7,
        questions.f_8,
        questions.f_9,
    ]),
    g: new QS("Set 5", [
        questions.g_0,
        questions.g_1,
        questions.g_2,
        questions.g_3,
        questions.g_4,
        questions.g_5,
        questions.g_6,
        questions.g_7,
        questions.g_8,
        questions.g_9,
    ]),
    h: new QS("Set 6", [
        questions.h_0,
        questions.h_1,
        questions.h_2,
        questions.h_3,
        questions.h_4,
        questions.h_5,
        questions.h_6,
        questions.h_7,
        questions.h_8,
        questions.h_9,
    ]),
    l: new QS("Set 7", [
        questions.l_0,
        questions.l_1,
        questions.l_2,
        questions.l_3,
        questions.l_4,
        questions.l_5,
        questions.l_6,
        questions.l_7,
        questions.l_8,
        questions.l_9,
    ]),
    m: new QS("Set 8", [
        questions.m_0,
        questions.m_1,
        questions.m_2,
        questions.m_3,
        questions.m_4,
        questions.m_5,
        questions.m_6,
        questions.m_7,
        questions.m_8,
        questions.m_9,
    ]),
    p: new QS("Set 9", [
        questions.p_0,
        questions.p_1,
        questions.p_2,
        questions.p_3,
        questions.p_4,
        questions.p_5,
        questions.p_6,
        questions.p_7,
        questions.p_8,
        questions.p_9,
    ]),
    sh: new QS("Set 10", [
        questions.sh_0,
        questions.sh_1,
        questions.sh_2,
        questions.sh_3,
        questions.sh_4,
        questions.sh_5,
        questions.sh_6,
        questions.sh_7,
        questions.sh_8,
        questions.sh_9,
    ]),
    t: new QS("Set 11", [
        questions.t_0,
        questions.t_1,
        questions.t_2,
        questions.t_3,
        questions.t_4,
        questions.t_5,
        questions.t_6,
        questions.t_7,
        questions.t_8,
        questions.t_9,
    ]),
    v: new QS("Set 12", [
        questions.v_0,
        questions.v_1,
        questions.v_2,
        questions.v_3,
        questions.v_4,
        questions.v_5,
        questions.v_6,
        questions.v_7,
        questions.v_8,
        questions.v_9,
    ]),
    w: new QS("Set 13", [
        questions.w_0,
        questions.w_1,
        questions.w_2,
        questions.w_3,
        questions.w_4,
        questions.w_5,
        questions.w_6,
        questions.w_7,
        questions.w_8,
        questions.w_9,
    ]),
};

class Activity {
    constructor(name, abbreviation, sets) {
        this.name = name;
        this.abbr = abbreviation;
        this.sets = sets;
    }
}

export const activities = {
    ipa: new Activity("Implicit Phoneme Manipulation", "IPM", [
        sets.b,
        sets.c,
        sets.d,
        sets.f,
        sets.g,
        sets.h,
        sets.l,
        sets.m,
        sets.p,
        sets.sh,
        sets.t,
        sets.v,
        sets.w,
    ]),
    pca: new Activity("Phonological Component Analysis", "PCA", [s.b]),
};
