const images = {
    baby: "images/image prompts/baby.jpg",
    balloon: "images/image prompts/balloon.jpg",
    banana: "images/image prompts/banana.jpg",
    basket: "images/image prompts/basket.jpg",
    bicycle: "images/image prompts/bicycle.jpg",
    bird: "images/image prompts/bird.jpg",
    boat: "images/image prompts/boat.jpg",
    bowl: "images/image prompts/bowl.jpg",
    bread: "images/image prompts/bread.jpg",
    burger: "images/image prompts/burger.jpg",
    cake: "images/image prompts/cake.jpg",
    camel: "images/image prompts/camel.jpg",
    candle: "images/image prompts/candle.jpg",
    car: "images/image prompts/car.jpg",
    carrot: "images/image prompts/carrot.jpg",
    cat: "images/image prompts/cat.jpg",
    cloud: "images/image prompts/cloud.jpg",
    coffee: "images/image prompts/coffee.jpg",
    cookie: "images/image prompts/cookie.jpg",
    crayon: "images/image prompts/crayon.jpg",
    dice: "images/image prompts/dice.jpg",
    dinosaur: "images/image prompts/dinosaur.jpg",
    doctor: "images/image prompts/doctor.jpg",
    dog: "images/image prompts/dog.jpg",
    dolphin: "images/image prompts/dolphin.jpg",
    donkey: "images/image prompts/donkey.jpg",
    donut: "images/image prompts/donut.jpg",
    door: "images/image prompts/door.jpg",
    drums: "images/image prompts/drums.jpg",
    duck: "images/image prompts/duck.jpg",
    feather: "images/image prompts/feather.jpg",
    feet: "images/image prompts/feet.jpg",
    fire: "images/image prompts/fire.jpg",
    fish: "images/image prompts/fish.jpg",
    flag: "images/image prompts/flag.jpg",
    flamingo: "images/image prompts/flamingo.jpg",
    flower: "images/image prompts/flower.jpg",
    fork: "images/image prompts/fork.jpg",
    fox: "images/image prompts/fox.jpg",
    frog: "images/image prompts/frog.jpg",
    giraffe: "images/image prompts/giraffe.jpg",
    girl: "images/image prompts/girl.jpg",
    glasses: "images/image prompts/glasses.jpg",
    goat: "images/image prompts/goat.jpg",
    goldfish: "images/image prompts/goldfish.jpg",
    gong: "images/image prompts/gong.jpg",
    gorilla: "images/image prompts/gorilla.jpg",
    grapes: "images/image prompts/grapes.jpg",
    grass: "images/image prompts/grass.jpg",
    guitar: "images/image prompts/guitar.jpg",
    hair: "images/image prompts/hair.jpg",
    hammer: "images/image prompts/hammer.jpg",
    hand: "images/image prompts/hand.jpg",
    harp: "images/image prompts/harp.jpg",
    hat: "images/image prompts/hat.jpg",
    hedgehog: "images/image prompts/hedgehog.jpg",
    helicopter: "images/image prompts/helicopter.jpg",
    hippo: "images/image prompts/hippo.jpg",
    horse: "images/image prompts/horse.jpg",
    house: "images/image prompts/house.jpg",
    ladder: "images/image prompts/ladder.jpg",
    ladybug: "images/image prompts/ladybug.jpg",
    lantern: "images/image prompts/lantern.jpg",
    lavender: "images/image prompts/lavender.jpg",
    leaf: "images/image prompts/leaf.jpg",
    lemon: "images/image prompts/lemon.jpg",
    leopard: "images/image prompts/leopard.jpg",
    lime: "images/image prompts/lime.jpg",
    lizard: "images/image prompts/lizard.jpg",
    lychee: "images/image prompts/lychee.jpg",
    marshmallow: "images/image prompts/marshmallow.jpg",
    massage: "images/image prompts/massage.jpg",
    match: "images/image prompts/match.jpg",
    meerkat: "images/image prompts/meerkat.jpg",
    microwave: "images/image prompts/microwave.jpg",
    milk: "images/image prompts/milk.jpg",
    money: "images/image prompts/money.jpg",
    monkey: "images/image prompts/monkey.jpg",
    mouse: "images/image prompts/mouse.jpg",
    mushroom: "images/image prompts/mushroom.jpg",
    paint: "images/image prompts/paint.jpg",
    pelican: "images/image prompts/pelican.jpg",
    pen: "images/image prompts/pen.jpg",
    pencil: "images/image prompts/pencil.jpg",
    penguin: "images/image prompts/penguin.jpg",
    pigeon: "images/image prompts/pigeon.jpg",
    pineapple: "images/image prompts/pineapple.jpg",
    pizza: "images/image prompts/pizza.jpg",
    plant: "images/image prompts/plant.jpg",
    popcorn: "images/image prompts/popcorn.jpg",
    shadow: "images/image prompts/shadow.jpg",
    shark: "images/image prompts/shark.jpg",
    sheep: "images/image prompts/sheep.jpg",
    sheep2: "images/image prompts/sheep2.jpg",
    shells: "images/image prompts/shells.jpg",
    ship: "images/image prompts/ship.jpg",
    shoe: "images/image prompts/shoe.jpg",
    shoes: "images/image prompts/shoes.jpg",
    shovel: "images/image prompts/shovel.jpg",
    shower: "images/image prompts/shower.jpg",
    tea: "images/image prompts/tea.jpg",
    television: "images/image prompts/television.jpg",
    tent: "images/image prompts/tent.jpg",
    tiger: "images/image prompts/tiger.jpg",
    toaster: "images/image prompts/toaster.jpg",
    tomato: "images/image prompts/tomato.jpg",
    train: "images/image prompts/train.jpg",
    tree: "images/image prompts/tree.jpg",
    turtle: "images/image prompts/turtle.jpg",
    typewriter: "images/image prompts/typewriter.jpg",
    vacuum: "images/image prompts/vacuum.jpg",
    van: "images/image prompts/van.jpg",
    vase: "images/image prompts/vase.jpg",
    vegebles: "images/image prompts/vegebles.jpg",
    vet: "images/image prompts/vet.jpg",
    vine: "images/image prompts/vine.jpg",
    violin: "images/image prompts/violin.jpg",
    volcano: "images/image prompts/volcano.jpg",
    volleyball: "images/image prompts/volleyball.jpg",
    vulture: "images/image prompts/vulture.jpg",
    waffle: "images/image prompts/waffle.jpg",
    wallet: "images/image prompts/wallet.jpg",
    walrus: "images/image prompts/walrus.jpg",
    watch: "images/image prompts/watch.jpg",
    water: "images/image prompts/water.jpg",
    watermelon: "images/image prompts/watermelon.jpg",
    whale: "images/image prompts/whale.jpg",
    wheat: "images/image prompts/wheat.jpg",
    window: "images/image prompts/window.jpg",
    wolf: "images/image prompts/wolf.jpg",
};

class Question {
    constructor(text, soundfile, correctimage, redherrings) {
        this.text = text;
        this.soundfile = soundfile;
        this.correctimage = correctimage;
        this.images = redherrings;
        this.images.push(correctimage);
    }
}

class SWQuestion extends Question {
    //Starts with question
    constructor(soundfile, correctimage, redherrings) {
        super(
            "Please click the image that starts with this sound:",
            soundfile,
            correctimage,
            redherrings
        );
    }
}

const questions = {
    ipa_sw_b_0: new SWQuestion("audio.mp3", images.baby, [
        images.cookie,
        images.pelican,
        images.van,
    ]),
    ipa_sw_b_1: new SWQuestion("audio.mp3", images.balloon, [
        images.tent,
        images.goat,
        images.car,
    ]),
    ipa_sw_b_2: new SWQuestion("audio.mp3", images.banana, [
        images.sheep,
        images.gong,
        images.pizza,
    ]),
    ipa_sw_b_3: new SWQuestion("audio.mp3", images.basket, [
        images.shoe,
        images.horse,
        images.toaster,
    ]),
    ipa_sw_b_4: new SWQuestion("audio.mp3", images.bicycle, [
        images.leopard,
        images.hippo,
        images.typewriter,
    ]),
    ipa_sw_b_5: new SWQuestion("audio.mp3", images.bird, [
        images.guitar,
        images.monkey,
        images.television,
    ]),
    ipa_sw_b_6: new SWQuestion("audio.mp3", images.boat, [
        images.shells,
        images.gorilla,
        images.giraffe,
    ]),
    ipa_sw_b_7: new SWQuestion("audio.mp3", images.bowl, [
        images.hair,
        images.donut,
        images.crayon,
    ]),
    ipa_sw_b_8: new SWQuestion("audio.mp3", images.bread, [
        images.whale,
        images.frog,
        images.volcano,
    ]),
    ipa_sw_b_9: new SWQuestion("audio.mp3", images.burger, [
        images.watermelon,
        images.popcorn,
        images.shoe,
    ]),
    ipa_sw_c_0: new SWQuestion("audio.mp3", images.cake, [
        images.gorilla,
        images.hippo,
        images.goldfish,
    ]),
    ipa_sw_c_1: new SWQuestion("audio.mp3", images.camel, [
        images.bicycle,
        images.fox,
        images.hammer,
    ]),
    ipa_sw_c_2: new SWQuestion("audio.mp3", images.candle, [
        images.lantern,
        images.pen,
        images.hammer,
    ]),
    ipa_sw_c_3: new SWQuestion("audio.mp3", images.car, [
        images.basket,
        images.leopard,
        images.baby,
    ]),
    ipa_sw_c_4: new SWQuestion("audio.mp3", images.carrot, [
        images.lavender,
        images.shells,
        images.flower,
    ]),
    ipa_sw_c_5: new SWQuestion("audio.mp3", images.cat, [
        images.fox,
        images.water,
        images.walrus,
    ]),
    ipa_sw_c_6: new SWQuestion("audio.mp3", images.cloud, [
        images.feet,
        images.pizza,
        images.massage,
    ]),
    ipa_sw_c_7: new SWQuestion("audio.mp3", images.coffee, [
        images.guitar,
        images.horse,
        images.hippo,
    ]),
    ipa_sw_c_8: new SWQuestion("audio.mp3", images.cookie, [
        images.whale,
        images.whale,
        images.door,
    ]),
    ipa_sw_c_9: new SWQuestion("audio.mp3", images.crayon, [
        images.ship,
        images.shoes,
        images.banana,
    ]),
    ipa_sw_d_0: new SWQuestion("audio.mp3", images.dice, [
        images.baby,
        images.toaster,
        images.watermelon,
    ]),
    ipa_sw_d_1: new SWQuestion("audio.mp3", images.dinosaur, [
        images.flag,
        images.violin,
        images.hedgehog,
    ]),
    ipa_sw_d_2: new SWQuestion("audio.mp3", images.doctor, [
        images.helicopter,
        images.cookie,
        images.shoe,
    ]),
    ipa_sw_d_3: new SWQuestion("audio.mp3", images.dog, [
        images.shark,
        images.basket,
        images.mushroom,
    ]),
    ipa_sw_d_4: new SWQuestion("audio.mp3", images.dolphin, [
        images.shadow,
        images.hedgehog,
        images.hippo,
    ]),
    ipa_sw_d_5: new SWQuestion("audio.mp3", images.donkey, [
        images.fish,
        images.cat,
        images.baby,
    ]),
    ipa_sw_d_6: new SWQuestion("audio.mp3", images.donut, [
        images.hat,
        images.water,
        images.balloon,
    ]),
    ipa_sw_d_7: new SWQuestion("audio.mp3", images.door, [
        images.mushroom,
        images.house,
        images.camel,
    ]),
    ipa_sw_d_8: new SWQuestion("audio.mp3", images.drums, [
        images.grapes,
        images.hippo,
        images.hippo,
    ]),
    ipa_sw_d_9: new SWQuestion("audio.mp3", images.duck, [
        images.lychee,
        images.glasses,
        images.shoes,
    ]),
    ipa_sw_f_0: new SWQuestion("audio.mp3", images.feather, [
        images.monkey,
        images.watermelon,
        images.pelican,
    ]),
    ipa_sw_f_1: new SWQuestion("audio.mp3", images.feet, [
        images.shells,
        images.mushroom,
        images.ladder,
    ]),
    ipa_sw_f_2: new SWQuestion("audio.mp3", images.fire, [
        images.penguin,
        images.pigeon,
        images.pigeon,
    ]),
    ipa_sw_f_3: new SWQuestion("audio.mp3", images.fish, [
        images.door,
        images.mouse,
        images.vulture,
    ]),
    ipa_sw_f_4: new SWQuestion("audio.mp3", images.flag, [
        images.bicycle,
        images.donkey,
        images.banana,
    ]),
    ipa_sw_f_5: new SWQuestion("audio.mp3", images.flamingo, [
        images.vine,
        images.shoes,
        images.vase,
    ]),
    ipa_sw_f_6: new SWQuestion("audio.mp3", images.flower, [
        images.dinosaur,
        images.mushroom,
        images.coffee,
    ]),
    ipa_sw_f_7: new SWQuestion("audio.mp3", images.fork, [
        images.wallet,
        images.sheep,
        images.baby,
    ]),
    ipa_sw_f_8: new SWQuestion("audio.mp3", images.fox, [
        images.dice,
        images.duck,
        images.bowl,
    ]),
    ipa_sw_f_9: new SWQuestion("audio.mp3", images.frog, [
        images.hippo,
        images.monkey,
        images.plant,
    ]),
    ipa_sw_g_0: new SWQuestion("audio.mp3", images.giraffe, [
        images.volcano,
        images.bird,
        images.water,
    ]),
    ipa_sw_g_1: new SWQuestion("audio.mp3", images.girl, [
        images.lychee,
        images.lantern,
        images.mushroom,
    ]),
    ipa_sw_g_2: new SWQuestion("audio.mp3", images.glasses, [
        images.sheep,
        images.window,
        images.shadow,
    ]),
    ipa_sw_g_3: new SWQuestion("audio.mp3", images.goat, [
        images.sheep,
        images.bowl,
        images.vine,
    ]),
    ipa_sw_g_4: new SWQuestion("audio.mp3", images.goldfish, [
        images.toaster,
        images.ladybug,
        images.lemon,
    ]),
    ipa_sw_g_5: new SWQuestion("audio.mp3", images.gong, [
        images.basket,
        images.harp,
        images.fork,
    ]),
    ipa_sw_g_6: new SWQuestion("audio.mp3", images.gorilla, [
        images.bicycle,
        images.marshmallow,
        images.meerkat,
    ]),
    ipa_sw_g_7: new SWQuestion("audio.mp3", images.grapes, [
        images.lime,
        images.vegebles,
        images.flamingo,
    ]),
    ipa_sw_g_8: new SWQuestion("audio.mp3", images.grass, [
        images.ladybug,
        images.shells,
        images.cookie,
    ]),
    ipa_sw_g_9: new SWQuestion("audio.mp3", images.guitar, [
        images.plant,
        images.monkey,
        images.paint,
    ]),
    ipa_sw_h_0: new SWQuestion("audio.mp3", images.hair, [
        images.doctor,
        images.flower,
        images.glasses,
    ]),
    ipa_sw_h_1: new SWQuestion("audio.mp3", images.hammer, [
        images.volleyball,
        images.shoe,
        images.turtle,
    ]),
    ipa_sw_h_2: new SWQuestion("audio.mp3", images.hand, [
        images.dog,
        images.flamingo,
        images.violin,
    ]),
    ipa_sw_h_3: new SWQuestion("audio.mp3", images.harp, [
        images.shoe,
        images.leopard,
        images.volcano,
    ]),
    ipa_sw_h_4: new SWQuestion("audio.mp3", images.hat, [
        images.lime,
        images.goldfish,
        images.leaf,
    ]),
    ipa_sw_h_5: new SWQuestion("audio.mp3", images.hedgehog, [
        images.banana,
        images.vase,
        images.vase,
    ]),
    ipa_sw_h_6: new SWQuestion("audio.mp3", images.helicopter, [
        images.paint,
        images.goldfish,
        images.grass,
    ]),
    ipa_sw_h_7: new SWQuestion("audio.mp3", images.hippo, [
        images.pineapple,
        images.flamingo,
        images.watch,
    ]),
    ipa_sw_h_8: new SWQuestion("audio.mp3", images.horse, [
        images.train,
        images.banana,
        images.sheep,
    ]),
    ipa_sw_h_9: new SWQuestion("audio.mp3", images.house, [
        images.television,
        images.pencil,
        images.ship,
    ]),
    ipa_sw_l_0: new SWQuestion("audio.mp3", images.ladder, [
        images.feet,
        images.train,
        images.drums,
    ]),
    ipa_sw_l_1: new SWQuestion("audio.mp3", images.ladybug, [
        images.water,
        images.toaster,
        images.whale,
    ]),
    ipa_sw_l_2: new SWQuestion("audio.mp3", images.lantern, [
        images.turtle,
        images.grapes,
        images.wolf,
    ]),
    ipa_sw_l_3: new SWQuestion("audio.mp3", images.lavender, [
        images.typewriter,
        images.bicycle,
        images.van,
    ]),
    ipa_sw_l_4: new SWQuestion("audio.mp3", images.leaf, [
        images.shoe,
        images.shells,
        images.donkey,
    ]),
    ipa_sw_l_5: new SWQuestion("audio.mp3", images.lemon, [
        images.goldfish,
        images.candle,
        images.sheep,
    ]),
    ipa_sw_l_6: new SWQuestion("audio.mp3", images.leopard, [
        images.bowl,
        images.pelican,
        images.goldfish,
    ]),
    ipa_sw_l_7: new SWQuestion("audio.mp3", images.lime, [
        images.microwave,
        images.shovel,
        images.cat,
    ]),
    ipa_sw_l_8: new SWQuestion("audio.mp3", images.lizard, [
        images.money,
        images.gorilla,
        images.hat,
    ]),
    ipa_sw_l_9: new SWQuestion("audio.mp3", images.lychee, [
        images.hippo,
        images.vegebles,
        images.basket,
    ]),
    ipa_sw_m_0: new SWQuestion("audio.mp3", images.marshmallow, [
        images.car,
        images.violin,
        images.horse,
    ]),
    ipa_sw_m_1: new SWQuestion("audio.mp3", images.massage, [
        images.lavender,
        images.carrot,
        images.flamingo,
    ]),
    ipa_sw_m_2: new SWQuestion("audio.mp3", images.match, [
        images.duck,
        images.fox,
        images.lime,
    ]),
    ipa_sw_m_3: new SWQuestion("audio.mp3", images.meerkat, [
        images.pen,
        images.giraffe,
        images.lizard,
    ]),
    ipa_sw_m_4: new SWQuestion("audio.mp3", images.microwave, [
        images.dinosaur,
        images.pencil,
        images.dog,
    ]),
    ipa_sw_m_5: new SWQuestion("audio.mp3", images.milk, [
        images.tiger,
        images.glasses,
        images.ladybug,
    ]),
    ipa_sw_m_6: new SWQuestion("audio.mp3", images.money, [
        images.cookie,
        images.glasses,
        images.pizza,
    ]),
    ipa_sw_m_7: new SWQuestion("audio.mp3", images.monkey, [
        images.tea,
        images.popcorn,
        images.pelican,
    ]),
    ipa_sw_m_8: new SWQuestion("audio.mp3", images.mouse, [
        images.cake,
        images.tree,
        images.waffle,
    ]),
    ipa_sw_m_9: new SWQuestion("audio.mp3", images.mushroom, [
        images.door,
        images.camel,
        images.ship,
    ]),
    ipa_sw_p_0: new SWQuestion("audio.mp3", images.paint, [
        images.burger,
        images.walrus,
        images.shark,
    ]),
    ipa_sw_p_1: new SWQuestion("audio.mp3", images.pelican, [
        images.harp,
        images.cookie,
        images.guitar,
    ]),
    ipa_sw_p_2: new SWQuestion("audio.mp3", images.pen, [
        images.typewriter,
        images.dog,
        images.fork,
    ]),
    ipa_sw_p_3: new SWQuestion("audio.mp3", images.pencil, [
        images.balloon,
        images.flower,
        images.bicycle,
    ]),
    ipa_sw_p_4: new SWQuestion("audio.mp3", images.penguin, [
        images.door,
        images.hippo,
        images.massage,
    ]),
    ipa_sw_p_5: new SWQuestion("audio.mp3", images.pigeon, [
        images.typewriter,
        images.hair,
        images.tea,
    ]),
    ipa_sw_p_6: new SWQuestion("audio.mp3", images.pineapple, [
        images.duck,
        images.leopard,
        images.ladybug,
    ]),
    ipa_sw_p_7: new SWQuestion("audio.mp3", images.pizza, [
        images.van,
        images.dog,
        images.helicopter,
    ]),
    ipa_sw_p_8: new SWQuestion("audio.mp3", images.plant, [
        images.van,
        images.turtle,
        images.lizard,
    ]),
    ipa_sw_p_9: new SWQuestion("audio.mp3", images.popcorn, [
        images.walrus,
        images.mushroom,
        images.typewriter,
    ]),
    ipa_sw_sh_0: new SWQuestion("audio.mp3", images.shadow, [
        images.goat,
        images.giraffe,
        images.waffle,
    ]),
    ipa_sw_sh_1: new SWQuestion("audio.mp3", images.shark, [
        images.money,
        images.boat,
        images.lychee,
    ]),
    ipa_sw_sh_2: new SWQuestion("audio.mp3", images.sheep, [
        images.feather,
        images.duck,
        images.popcorn,
    ]),
    ipa_sw_sh_3: new SWQuestion("audio.mp3", images.sheep2, [
        images.feet,
        images.wolf,
        images.monkey,
    ]),
    ipa_sw_sh_4: new SWQuestion("audio.mp3", images.shells, [
        images.cloud,
        images.cookie,
        images.crayon,
    ]),
    ipa_sw_sh_5: new SWQuestion("audio.mp3", images.ship, [
        images.dog,
        images.crayon,
        images.horse,
    ]),
    ipa_sw_sh_6: new SWQuestion("audio.mp3", images.shoe, [
        images.lantern,
        images.vegebles,
        images.penguin,
    ]),
    ipa_sw_sh_7: new SWQuestion("audio.mp3", images.shoes, [
        images.grapes,
        images.leopard,
        images.pineapple,
    ]),
    ipa_sw_sh_8: new SWQuestion("audio.mp3", images.shovel, [
        images.fork,
        images.turtle,
        images.massage,
    ]),
    ipa_sw_sh_9: new SWQuestion("audio.mp3", images.shower, [
        images.drums,
        images.vase,
        images.paint,
    ]),
    ipa_sw_t_0: new SWQuestion("audio.mp3", images.tea, [
        images.house,
        images.plant,
        images.shadow,
    ]),
    ipa_sw_t_1: new SWQuestion("audio.mp3", images.television, [
        images.watch,
        images.pizza,
        images.van,
    ]),
    ipa_sw_t_2: new SWQuestion("audio.mp3", images.tent, [
        images.basket,
        images.waffle,
        images.house,
    ]),
    ipa_sw_t_3: new SWQuestion("audio.mp3", images.tiger, [
        images.pigeon,
        images.pelican,
        images.violin,
    ]),
    ipa_sw_t_4: new SWQuestion("audio.mp3", images.toaster, [
        images.duck,
        images.lychee,
        images.monkey,
    ]),
    ipa_sw_t_5: new SWQuestion("audio.mp3", images.tomato, [
        images.hat,
        images.gong,
        images.drums,
    ]),
    ipa_sw_t_6: new SWQuestion("audio.mp3", images.train, [
        images.lime,
        images.lime,
        images.donut,
    ]),
    ipa_sw_t_7: new SWQuestion("audio.mp3", images.tree, [
        images.pigeon,
        images.microwave,
        images.water,
    ]),
    ipa_sw_t_8: new SWQuestion("audio.mp3", images.turtle, [
        images.pen,
        images.vulture,
        images.van,
    ]),
    ipa_sw_t_9: new SWQuestion("audio.mp3", images.typewriter, [
        images.bird,
        images.door,
        images.microwave,
    ]),
    ipa_sw_v_0: new SWQuestion("audio.mp3", images.vacuum, [
        images.boat,
        images.bicycle,
        images.train,
    ]),
    ipa_sw_v_1: new SWQuestion("audio.mp3", images.van, [
        images.hair,
        images.pelican,
        images.shower,
    ]),
    ipa_sw_v_2: new SWQuestion("audio.mp3", images.vase, [
        images.water,
        images.fork,
        images.tomato,
    ]),
    ipa_sw_v_3: new SWQuestion("audio.mp3", images.vegebles, [
        images.train,
        images.television,
        images.match,
    ]),
    ipa_sw_v_4: new SWQuestion("audio.mp3", images.vet, [
        images.feet,
        images.donkey,
        images.harp,
    ]),
    ipa_sw_v_5: new SWQuestion("audio.mp3", images.vine, [
        images.monkey,
        images.sheep,
        images.feather,
    ]),
    ipa_sw_v_6: new SWQuestion("audio.mp3", images.violin, [
        images.shark,
        images.hand,
        images.walrus,
    ]),
    ipa_sw_v_7: new SWQuestion("audio.mp3", images.volcano, [
        images.dice,
        images.match,
        images.boat,
    ]),
    ipa_sw_v_8: new SWQuestion("audio.mp3", images.volleyball, [
        images.coffee,
        images.paint,
        images.match,
    ]),
    ipa_sw_v_9: new SWQuestion("audio.mp3", images.vulture, [
        images.lizard,
        images.hat,
        images.balloon,
    ]),
    ipa_sw_w_0: new SWQuestion("audio.mp3", images.waffle, [
        images.shoe,
        images.marshmallow,
        images.fox,
    ]),
    ipa_sw_w_1: new SWQuestion("audio.mp3", images.wallet, [
        images.pen,
        images.plant,
        images.cloud,
    ]),
    ipa_sw_w_2: new SWQuestion("audio.mp3", images.walrus, [
        images.lemon,
        images.ship,
        images.donkey,
    ]),
    ipa_sw_w_3: new SWQuestion("audio.mp3", images.watch, [
        images.doctor,
        images.dog,
        images.cat,
    ]),
    ipa_sw_w_4: new SWQuestion("audio.mp3", images.water, [
        images.gorilla,
        images.donut,
        images.microwave,
    ]),
    ipa_sw_w_5: new SWQuestion("audio.mp3", images, [
        images.mouse,
        images.grapes,
        images.gong,
    ]),
    ipa_sw_w_6: new SWQuestion("audio.mp3", images.whale, [
        images.volcano,
        images.grapes,
        images.shovel,
    ]),
    ipa_sw_w_7: new SWQuestion("audio.mp3", images.wheat, [
        images.doctor,
        images.bowl,
        images.hand,
    ]),
    ipa_sw_w_8: new SWQuestion("audio.mp3", images.window, [
        images.mushroom,
        images.pelican,
        images.camel,
    ]),
    ipa_sw_w_9: new SWQuestion("audio.mp3", images.wolf, [
        images.shovel,
        images.giraffe,
        images.frog,
    ]),
};

class QuestionSet {
    constructor(name, questions) {
        this.name = name;
        this.activities = questions;
    }
}

const sets = {
    ipa_sw_b: new QuestionSet("Set 1", [
        questions.ipa_sw_b_0,
        questions.ipa_sw_b_1,
        questions.ipa_sw_b_2,
        questions.ipa_sw_b_3,
        questions.ipa_sw_b_4,
        questions.ipa_sw_b_5,
        questions.ipa_sw_b_6,
        questions.ipa_sw_b_7,
        questions.ipa_sw_b_8,
        questions.ipa_sw_b_9,
    ]),
    ipa_sw_c: new QuestionSet("Set 2", [
        questions.ipa_sw_c_0,
        questions.ipa_sw_c_1,
        questions.ipa_sw_c_2,
        questions.ipa_sw_c_3,
        questions.ipa_sw_c_4,
        questions.ipa_sw_c_5,
        questions.ipa_sw_c_6,
        questions.ipa_sw_c_7,
        questions.ipa_sw_c_8,
        questions.ipa_sw_c_9,
    ]),
    ipa_sw_d: new QuestionSet("Set 3", [
        questions.ipa_sw_d_0,
        questions.ipa_sw_d_1,
        questions.ipa_sw_d_2,
        questions.ipa_sw_d_3,
        questions.ipa_sw_d_4,
        questions.ipa_sw_d_5,
        questions.ipa_sw_d_6,
        questions.ipa_sw_d_7,
        questions.ipa_sw_d_8,
        questions.ipa_sw_d_9,
    ]),
    ipa_sw_f: new QuestionSet("Set 4", [
        questions.ipa_sw_f_0,
        questions.ipa_sw_f_1,
        questions.ipa_sw_f_2,
        questions.ipa_sw_f_3,
        questions.ipa_sw_f_4,
        questions.ipa_sw_f_5,
        questions.ipa_sw_f_6,
        questions.ipa_sw_f_7,
        questions.ipa_sw_f_8,
        questions.ipa_sw_f_9,
    ]),
    ipa_sw_g: new QuestionSet("Set 5", [
        questions.ipa_sw_g_0,
        questions.ipa_sw_g_1,
        questions.ipa_sw_g_2,
        questions.ipa_sw_g_3,
        questions.ipa_sw_g_4,
        questions.ipa_sw_g_5,
        questions.ipa_sw_g_6,
        questions.ipa_sw_g_7,
        questions.ipa_sw_g_8,
        questions.ipa_sw_g_9,
    ]),
    ipa_sw_h: new QuestionSet("Set 6", [
        questions.ipa_sw_h_0,
        questions.ipa_sw_h_1,
        questions.ipa_sw_h_2,
        questions.ipa_sw_h_3,
        questions.ipa_sw_h_4,
        questions.ipa_sw_h_5,
        questions.ipa_sw_h_6,
        questions.ipa_sw_h_7,
        questions.ipa_sw_h_8,
        questions.ipa_sw_h_9,
    ]),
    ipa_sw_l: new QuestionSet("Set 7", [
        questions.ipa_sw_l_0,
        questions.ipa_sw_l_1,
        questions.ipa_sw_l_2,
        questions.ipa_sw_l_3,
        questions.ipa_sw_l_4,
        questions.ipa_sw_l_5,
        questions.ipa_sw_l_6,
        questions.ipa_sw_l_7,
        questions.ipa_sw_l_8,
        questions.ipa_sw_l_9,
    ]),
    ipa_sw_m: new QuestionSet("Set 8", [
        questions.ipa_sw_m_0,
        questions.ipa_sw_m_1,
        questions.ipa_sw_m_2,
        questions.ipa_sw_m_3,
        questions.ipa_sw_m_4,
        questions.ipa_sw_m_5,
        questions.ipa_sw_m_6,
        questions.ipa_sw_m_7,
        questions.ipa_sw_m_8,
        questions.ipa_sw_m_9,
    ]),
    ipa_sw_p: new QuestionSet("Set 9", [
        questions.ipa_sw_p_0,
        questions.ipa_sw_p_1,
        questions.ipa_sw_p_2,
        questions.ipa_sw_p_3,
        questions.ipa_sw_p_4,
        questions.ipa_sw_p_5,
        questions.ipa_sw_p_6,
        questions.ipa_sw_p_7,
        questions.ipa_sw_p_8,
        questions.ipa_sw_p_9,
    ]),
    ipa_sw_sh: new QuestionSet("Set 10", [
        questions.ipa_sw_sh_0,
        questions.ipa_sw_sh_1,
        questions.ipa_sw_sh_2,
        questions.ipa_sw_sh_3,
        questions.ipa_sw_sh_4,
        questions.ipa_sw_sh_5,
        questions.ipa_sw_sh_6,
        questions.ipa_sw_sh_7,
        questions.ipa_sw_sh_8,
        questions.ipa_sw_sh_9,
    ]),
    ipa_sw_t: new QuestionSet("Set 11", [
        questions.ipa_sw_t_0,
        questions.ipa_sw_t_1,
        questions.ipa_sw_t_2,
        questions.ipa_sw_t_3,
        questions.ipa_sw_t_4,
        questions.ipa_sw_t_5,
        questions.ipa_sw_t_6,
        questions.ipa_sw_t_7,
        questions.ipa_sw_t_8,
        questions.ipa_sw_t_9,
    ]),
    ipa_sw_v: new QuestionSet("Set 12", [
        questions.ipa_sw_v_0,
        questions.ipa_sw_v_1,
        questions.ipa_sw_v_2,
        questions.ipa_sw_v_3,
        questions.ipa_sw_v_4,
        questions.ipa_sw_v_5,
        questions.ipa_sw_v_6,
        questions.ipa_sw_v_7,
        questions.ipa_sw_v_8,
        questions.ipa_sw_v_9,
    ]),
    ipa_sw_w: new QuestionSet("Set 13", [
        questions.ipa_sw_w_0,
        questions.ipa_sw_w_1,
        questions.ipa_sw_w_2,
        questions.ipa_sw_w_3,
        questions.ipa_sw_w_4,
        questions.ipa_sw_w_5,
        questions.ipa_sw_w_6,
        questions.ipa_sw_w_7,
        questions.ipa_sw_w_8,
        questions.ipa_sw_w_9,
    ]),
};

class Activity {
    constructor(name, abbreviation, sets) {
        this.name = name;
        this.abbr = abbreviation;
        this.sets = sets;
    }
}

export const activities = {
    ipa: new Activity("Implicit Phoneme Manipulation", "IPM", [
        sets.ipa_sw_b,
        sets.ipa_sw_c,
        sets.ipa_sw_d,
        sets.ipa_sw_f,
        sets.ipa_sw_g,
        sets.ipa_sw_h,
        sets.ipa_sw_l,
        sets.ipa_sw_m,
        sets.ipa_sw_p,
        sets.ipa_sw_sh,
        sets.ipa_sw_t,
        sets.ipa_sw_v,
        sets.ipa_sw_w,
    ]),
    pca: new Activity("Phonological Component Analysis", "PCA", [
        sets.ipa_sw_b,
    ]),
};
